### ISSUE TITLE
Question: using the anythread + OS mode counting

### ISSUE THREAD

**Issue by travisdowns** [obilaniu/libpfc#14]
How do we do it use it? Do we just OR the PFC_CFG value with with 0b100 and 0b001? Does `parseCfg` support it?

**Comment by obilaniu** [comment]
@travisdowns Right now `pfcParseConfig()` hasn't learned yet a syntax for specifying the anythread/OS bit, so

- For fixed-function counters you must OR the config with `0b100` (AnyThread) and `0b001` (OS),
- For general-purpose counters you must OR the config with `0x200000` (AnyThread) and `0x20000` (OS).

It's on the slate of things to be done. Maybe I could teach `libpfc` the `:u`, `:k`, `:uk` syntax of `perf`.

**Comment by obilaniu** [comment]
@travisdowns For general-purpose counter programming, event configurations parseable by `pfcParseCfg()`, now support a suffix `:` plus any combination of letters `auk`.

E.g.

    *cpl_cycles.ring0>=1:uk

is an edge-triggered (`*`), User (`:u`) and OS (`:k`)-counting event that only counts on _this_ thread (no `:a` for AnyThread).

**Comment by obilaniu** [comment]
But for fixed-function counters, whose configs are nowhere near the same format, it's still an ugly bitfield

    Bit 3: Interrupt Enable
    Bit 2: AnyThread
    Bit 1: User Mode
    Bit 0: OS Mode

If you have ideas for how to unify these two representations that would be great.

**Comment by travisdowns** [comment]
What's the default u/k mode if neither `u` nor `k` is specified?

**Comment by obilaniu** [comment]
@travisdowns It's `:u`, meaning 1) user 2) no OS 3) this thread only.
