### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by andreas-abel** [obilaniu/libpfc#3]
Is this project available under an open-source license? In particular, I would be interested if I am allowed to use (and modify) parts of the code in my own project.

(More information about licensing on GitHub is available here: https://help.github.com/articles/licensing-a-repository/)

**Comment by obilaniu** [comment]
@andreas-abel Yes, and yes you may. Frankly I'm not a big lover of licenses, but now that people ask I'll license it MIT.

My only real red line is that I don't like it when anyone "blames" themselves for something they've not done (like claiming they've written code they've not written), or "blame" someone for their own actions (like the code being buggy when it explicitly comes without warranty, only a hope it might be useful).
