### ISSUE TITLE
CPUs that do not allow full-width writes are not supported

### ISSUE THREAD

**Issue by andreas-abel** [obilaniu/libpfc#4]
Using the kernel module on a CPU that does not support full-width writes (see section 18.2.5 in Intel 64 and IA-32 Architectures Software Developer’s Manual), like my Nehalem CPU, leads to a crash when loading the module.

**Comment by obilaniu** [comment]
@andreas-abel Does #5 with my extra changes solve this? If so either you or I could close this as solved.
