### ISSUE TITLE
Question: why set the counter values in pfcdemo?

### ISSUE THREAD

**Issue by travisdowns** [obilaniu/libpfc#9]
This is a question.

In noticed in pfcdemo, after setting up the counter configuration `pfcWrConfigs`, the counter value are zeroed out: `pfcWrCnts(0, 7, ZERO_CNT);`.

What is the purpose of this line? As far as I can tell (and anything else wouldn't work), all the measurements of the code between `PFCSTART` and `PFCEND` are based taking the delta of the the counter values, so I am curious if this line is needed in consumers (and when to issue it).

**Comment by obilaniu** [comment]
There is no real reason for it at all. It may date back to a previous era when that was really needed.

**Comment by travisdowns** [comment]
Thanks. It crossed my mind that it might be because there is a functionality to interrupt once a counter overflows (or reaches a set threshold?). I'm not sure how `libpfc` interacts with that functionality. That is, I know it doesn't use it, but could the counters somehow be set up to interrupt before libpfc reprogrammed them?

**Comment by obilaniu** [comment]
AFAIK I disable all interrupts on overflow within pfc.ko, and use no interrupt functionality whatsoever. The counters will simply wrap modulo power of 2.

**Comment by travisdowns** [comment]
Great. I consider this issue closed.

**Comment by obilaniu** [comment]
@travisdowns Kk I'll close #9.

By the way I am interested in maintaining this little library, but I'm right now under serious and sustained time pressure to complete other research work, so I cannot dedicate as much time as I'd like to `libpfc`. I do remember ideas such as having `pfcInit()` check that `rdpmc == 2` and suchlike, and eventually will add that.

**Comment by travisdowns** [comment]
Yes of course, there is no expectation from my part that you put any time into this code which you have already freely provided to everyone.

I am working on improvements as well as part of my use of this library in [uarch-bench](https://github.com/travisdowns/uarch-bench/issues/3), including a CR4.PCE check and I can put in that `rdpmc == 2` check as well (but annoyingly it seems that the file is only readable by root), so this would only work for processes running as root.

I will send you the pull requests in case you are interested in these improvements, look at them whenever you have time.
